#allow horses to swim
doHorsesSwim = true

#Blacklist
[blacklist]
	#list of resourcelocations in string form
	blacklist = [""]

#Whitelist
[whitelist]
	#list of resourcelocations in string form
	whitelist = ["minecraft:horse", "minecraft:strider", "alexsmobs:crow", "alexsmobs:elephant", "alexsmobs:gorilla", "alexsmobs:grizzly_bear", "alexsmobs:tasmanian_devil", "alexsmobs:capuchin_monkey"]

