#If false, Wandering Traders will not sell any Generic Ecosphere items. If changed, a MC restart is required
wanderingTraderExtraTrades = true
#If false, Villagers will not sell any Generic Ecosphere items. If changed, a MC restart is required
villagerExtraTrades = true
#If false, all sub-biomes will not generate; does not affect vanilla biomes. If changed, a MC restart is required
subBiomes = true
#If false, island biomes will not generate. If changed, a MC restart is required
islandBiomes = true
#If false, beach and river variants will not generate, which does not affect vanilla biome variants. If changed, a MC restart is required
riversAndBeaches = true
#If false, vanilla biomes will not have extra features added to them. If changed, a MC restart is required
enhanceVanillaBiomes = false
#If false, dangerous blocks such as thorny bushes will not generate in the world. If changed, a MC restart is required
dangerousBlocks = true
#Biome Weights, zero means the biome will not appear; note that disabling certain biomes will cause some their sub-biomes to not appear. If changes are made, a MC restart is required
"Alder Forest Weight" = 6
"Alps Weight" = 5
"Appalachian Mountains Weight" = 5
"Ash Forest Weight" = 5
"Aspen Forest Weight" = 5
"Golden Aspen Forest Weight" = 0.25
"Autumnal Valley Weight" = 0
"Balsa Forest Weight" = 3
"Bamboo Forest Weight" = 0
"Baobab Savanna Weight" = 1
"Basswood Forest Weight" = 4
"Bayou Weight" = 0
"Beech Woods Weight" = 1
"Bog Weight" = 3
"Boreal Forest Weight" = 5
"Brushland Weight" = 2
"Butternut Woods Weight" = 4
"Bushland Weight" = 10
"Canyon Weight" = 2
"Cedar Forest Weight" = 5
"Chaparral Weight" = 5
"Cherry Blossom Forest Weight" = 0
"Chestnut Forest Weight" = 2
"Cold Desert Weight" = 1
"Coniferous Forest Weight" = 7
"Crag Weight" = 1
"Cypress Grove Weight" = 1
"Dark Swampland Weight" = 1
"Dense Forest Weight" = 1
"Douglas Forest Weight" = 5
"Dogwood Forest Weight" = 3
"Dryland Weight" = 1
"Dunes Weight" = 0
"Dying Forest Weight" = 2
"Dying Swamp Weight" = 1
"Ebony Forest Weight" = 1
"Elm Forest Weight" = 5
"Eucalyptus Forest Weight" = 1
"Evergreen Forest Weight" = 5
"Fen Weight" = 2
"Fir Forest Weight" = 5
"Flowering Fields Weight" = 4
"Fungal Woodland Weight" = 1
"Ginkgo Woods Weight" = 3
"Grassland Weight" = 19
"Great Lakes Weight" = 0
"Grove Weight" = 5
"Hazel Woods Weight" = 4
"Heathland Weight" = 3
"Hemlock Forest Weight" = 3
"Hickory Woodland Weight" = 3
"Highland Weight" = 4
"Holly Forest Weight" = 7
"Hornbeam Forest Weight" = 4
"Icy Forest Weight" = 1
"Jacaranda Grove Weight" = 0
"Japanese Maple Forest Weight" = 0
"Juniper Grove Weight" = 2
"Kapok Jungle Weight" = 1
"Cold Lake Weight" = 1
"Lake Weight" = 3
"Lukewarm Lake Weight" = 1
"Larch Taiga Weight" = 5
"Lavender Fields Weight" = 0
"Linden Forest Weight" = 1
"Lush Badlands Weight" = 1
"Lush Desert Weight" = 1
"Lush Savanna Weight" = 2
"Lush Swamp Weight" = 2
"Magnolia Grove Weight" = 1
"Mahogany Forest Weight" = 3
"Mangrove Marsh Weight" = 1
"Maple Forest Weight" = 0
"Maple Taiga Weight" = 0
"Marsh Weight" = 0
"Marula Savanna Weight" = 1
"Meadow Weight" = 10
"Mire Weight" = 2
"Mixed Forest Weight" = 5
"Moor Weight" = 2
"Mountain Weight" = 4
"Muskeg Weight" = 2
"Needle Forest Weight" = 1
"Oak Woodland Weight" = 9
"Outback Weight" = 2
"Orchard Weight" = 0
"Overgrown Cliffs Weight" = 1
"Pine Taiga Weight" = 5
"Plane Forest Weight" = 5
"Poplar Grove Weight" = 5
"Prairie Weight" = 8
"Quagmire Weight" = 1
"Rainbow Eucalyptus Forest Weight" = 1
"Rainforest Weight" = 1
"Red Desert Weight" = 2
"Redwood Forest Weight" = 1
"Robinia Woodland Weight" = 4
"Rosewood Weight" = 1
"Seasonal Forest Weight" = 0
"Scrubland Weight" = 9
"Sequoia Valley Weight" = 1
"Shield Weight" = 3
"Shrubland Weight" = 12
"Snowy Birch Forest Weight" = 3
"Snowy Evergreen Forest Weight" = 3
"Snowy Coniferous Forest Weight" = 3
"Snowy Dying Forest Weight" = 1
"Snowy Forest Weight" = 3
"Steppe Weight" = 3
"Thicket Weight" = 4
"Temperate Rainforest Weight" = 2
"Tropical Rainforest Weight" = 1
"Tundra Weight" = 5
"Walnut Forest Weight" = 3
"Wisteria Forest Weight" = 1
"Wetland Weight" = 3
"Xeric Shrubland Weight" = 4
"Yew Woods Weight" = 5
"Zelkova Forest Weight" = 3
"Mystical Valley Weight" = 1
"Sinister Forest Weight" = 1

