
#General configuration settings
[general]
	scaledProjectiles = true
	scaledReach = true
	scaledHealth = true
	scaledExplosions = true
	#Range: 16.0 ~ 128.0
	largeScaleCollisionThreshold = 26.0
	accurateNetherPortals = true
	scaledDefense = true
	scaledFallDamage = true
	scaledAttack = true
	scaledItemDrops = true
	keepAllScalesOnRespawn = false
	scaledMotion = true
	scalesKeptOnRespawn = []

