"Enable Wither" = true
"Enable Dragon" = true

[Wither]
	#Bonus Experience and Drops
	"Enable Rewards" = true
	#How difficulty is handled for the Wither. Disabling this "Feature" will disable all the Dragon changes.
	"Enable Difficulty Settings" = true
	#Makes the Wither smarter (will no longer try to stand on the player's head ...) and attack faster below Half Health
	"Enable Attack" = true
	#Handles the Damage Resistances and Vulnerabilities
	"Enable Resistances & Vulnerabilities" = true
	#Bonus Health and Bonus regeneration. The feature even fixes the Wither health bar not updating on spawn.
	"Enable Health" = true
	#Wither will spawn deadly (and tall) Minions
	"Enable Minions" = true
	#Handles various small features, such as the explosion
	"Enable Misc" = true

	#Bonus Health and Bonus regeneration. The feature even fixes the Wither health bar not updating on spawn.
	[Wither.Health]
		#Increase Wither's Health by this value per difficulty
		#Range: 0.0 ~ 1.7976931348623157E308
		"Health Bonus per Difficulty" = 10.0
		#How many half hearts will the Wither regen more per difficulty. This doesn't affect the natural regeneration of the Wither (1 Health per Second). (E.g. By default, with 6 Withers spawned, the Wither will heal 1.3 health per second).
		#Range: 0.0 ~ 1.7976931348623157E308
		"Bonus Regeneration per Difficulty" = 0.05
		#Maximum bonus regeneration per second given by "Bonus Regeneration per Difficulty". Set to 0 to disable bonus health regeneration. This doesn't affect the natural regeneration of the Wither (1 Health per Second). It's not recommended to go over 1.0f without mods that adds stronger things to kill the Wither
		#Range: 0.0 ~ 1.7976931348623157E308
		"Maximum Bonus Regeneration" = 1.0

	#Handles various small features, such as the explosion
	[Wither.Misc]
		#The Wither will try to not get stuck in bedrock for easy killing.
		"Prevent Getting Stuck" = true
		#At this difficulty the Wither Explosion will cause fire. Set to -1 to disable.
		#Range: > -1
		"Explosion Causes Fire at Difficulty" = 10
		#How much explosion power (after the invulnerability) will the Wither gain for each difficulty point. Explosion Radius is capped to 13. Base Wither Explosion Power is 7.0. Setting this to 0 will not increase the Wither Explosion Power.
		#Range: 0.0 ~ 4.0
		"Explosion Power Bonus" = 0.08

	#Makes the Wither smarter (will no longer try to stand on the player's head ...) and attack faster below Half Health
	[Wither.Attack]
		#The middle head will attack twice as fast when the Wither drops below half health.
		"Twice Attack Speed on Half Health" = true
		#If the AI changes should be applied to the first wither spawned too.
		"Apply to Vanilla Wither" = true

	#Handles the Damage Resistances and Vulnerabilities
	[Wither."Resistances & Vulnerabilities"]
		#Cap for 'Damage reduction per Difficulty below half health'
		#Range: 0.0 ~ 100.0
		"Max Damage reduction per Difficulty below half health" = 35.0
		#Bonus magic damage based off missing health. 150 means that every 150 missing health the damage will be amplified by 100%. E.g. The difficulty = 0 Wither (with 300 max health) is at half health (so it's missing 150hp), on magic damage he will receive 'magic_damage * (missing_health / magic_damage_bonus + 1)' = 'magic_damage * (150 / 150 + 1)' = 'magic_damage * 2'.
		#Range: 0.0 ~ 1024.0
		"Magic Damage Bonus" = 200.0
		#Percentage Damage Resistance as the Wither drops below half health.
		#Range: 0.0 ~ 100.0
		"Damage reduction per Difficulty below half health" = 4.0

	#Wither will spawn deadly (and tall) Minions
	[Wither.Minions]
		#Percentage bonus speed per difficulty.
		#Range: 0.0 ~ 1.7976931348623157E308
		"Bonus Movement Speed Per Difficulty" = 1.0
		#As the Wither starts spawning Minions, every how much difficulty the Wither will spawn one more Minion
		#Range: > 0
		"Bonus Minion Every Difficulty" = 2
		#Maximum amount of Minions that can be around the Wither in a 32 block radius. After this number is reached the Wither will stop spawning minions. Set to 0 to disable this check
		#Range: > 0
		"Max Minions Around" = 16
		#Maximum Minions spawned by the Wither
		#Range: > 0
		"Max Minions Spawned" = 8
		#Maximum ticks (20 ticks = 1 seconds) after Minions can spwan.
		#Range: > 0
		"Maximum Cooldown" = 480
		#Min and Max cooldowns are multiplied by this value when the Wither drops below half health. Set to 1 to not change the cooldown when the wither's health drops below half.
		#Range: 0.0 ~ 1.7976931348623157E308
		"Cooldown Multiplier Below Half Health" = 0.5
		#Wither Minions will die when the Wither that spawned them dies. (Note: only minions in a 128 blocks radius will be killed)
		"Kill Minions on Wither Death" = true
		#At which difficulty the Wither starts spawning Minions
		#Range: > 0
		"Minion at Difficulty" = 1
		#Minimum ticks (20 ticks = 1 seconds) after Minions can spwan.
		#Range: > 0
		"Minimum Cooldown" = 240

		[Wither.Minions.Equipment]
			#Chance for the Wither Minion to spawn with a bow when Wither's below Half Health
			#Range: 0.0 ~ 100.0
			"Bow Chance Below Half Health" = 0.08
			#Wither Minions will spawn with a Stone Sword
			"Has Sword" = true
			#Chance for the Wither Minion to spawn with a bow when Wither's above Half Health
			#Range: 0.0 ~ 100.0
			"Bow Chance Over Half Health" = 0.6

	#How difficulty is handled for the Wither. Disabling this "Feature" will disable all the Dragon changes.
	[Wither."Difficulty Settings"]
		#If true and there are more players around the Wither, the Wither will have his stats based on the sum of both players difficulty. If false, the Wither stats will be based on the average of the difficulty of the players around
		"Sum Spawned Wither Difficulty" = false
		#The Maximum difficulty (times spawned) reachable by Wither. By default is set to 72 because the Wither reaches the maximum amount of health (1024, capped by Minecraft. Some mods can increase this) after 72 withers spawned.
		#Range: > 1
		"Max Difficulty" = 72
		#How much difficulty will players start with when joining a world?
		#Range: > 0
		"Starting Difficulty" = 0
		#How much blocks from wither will be scanned for players to check for difficulty
		#Range: > 16
		"Spawn Radius Player Check" = 128

	#Bonus Experience and Drops
	[Wither.Rewards]
		#How much more experience (percentage) will Wither drop per Difficulty. The percentage is additive (e.g. with this set to 10%, 7 withers spawned = 70% more experience)
		#Range: 0.0 ~ 1.7976931348623157E308
		"Bonus Experience per Difficulty" = 10.0
		#A list of drops for the Withers. Entry format: item,amount,difficulty_required,chance,difficulty_mode,chance_mode
		#item: item id
		#amount: amount
		#difficulty_required: the amount of difficulty required for the item to drop, works differently based on mode
		#chance: chance for the drop to happen
		#difficulty_mode:
		#* MINIMUM: will try to drop the item when the difficulty matches or is higher
		#chance_mode:
		#* FLAT: chance is the percentage chance for the item to drop if the difficulty criteria matches
		#* SCALING: each point of difficulty >= 'difficulty to drop the item' will be multiplied by the chance (e.g. chance 2% and difficulty 10, difficulty required 5, chance to drop the item will be chance * (difficulty - difficulty_required + 1) = 2% * (10 - 5 + 1) = 12%)
		#By default Withers have 2% chance per difficulty >= 2 to drop 1 shard + 4% chance per difficulty >= 4 to drop 2 shards + 8% chance per difficulty >= 8 to drop 4 shards.
		Drops = ["progressivebosses:nether_star_shard,1,2,2,MINIMUM,SCALING", "progressivebosses:nether_star_shard,2,4,4,MINIMUM,SCALING", "progressivebosses:nether_star_shard,3,6,6,MINIMUM,SCALING", "progressivebosses:nether_star_shard,4,8,8,MINIMUM,SCALING"]

[Dragon]
	#How difficulty is handled for the Dragon. Disabling this "Feature" will disable all the Dragon changes.
	"Enable Difficulty Settings" = true

	#How difficulty is handled for the Dragon. Disabling this "Feature" will disable all the Dragon changes.
	[Dragon."Difficulty Settings"]
		#The Maximum difficulty (times killed) reachable by Ender Dragon. By default is set to 82 because the Ender Dragon reaches the maximum amount of health (1024, handled by Minecraft. Some mods can increase this) after 82 Dragons killed.
		#Range: > 1
		"Max Difficulty" = 82
		#How much difficulty will players start with when joining a world?
		#Range: > 0
		"Starting Difficulty" = 0
		#If true and there are more players around the Dragon, she will have his stats based on the sum of both players' difficulty. If false, the Dragon stats will be based on the average of the difficulty of the players around.
		"Sum Killed Dragons Difficulty" = false

